name: CI Workflow

on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3
    - name: install dependencies
      run : npm install

    - name: Run test with jest and supertest
      run: npm test